Update build.gradle to use latest Stitch SDKs
It was using the old 4.0.0 stitch SDKs which bundled the old embedded Java driver which used the old MongoDB embedded SDK ABI. The end result is runtime errors like this:
com.mongodb.embedded.client.MongoClientEmbeddedException: Error from embedded server when calling 'status_create': Error looking up function 'libmongodbcapi_status_create': undefined symbol: libmongodbcapi_status_create

This is because the the Embedded C API symbols were versioned and renamed about 7 weeks ago with this patch:
https://github.com/mongodb/mongo/commit/424dc423aff51129ef64ff109c7288330570fa28

I've updated the build file to use the latest Stitch SDKs as of today -- 4.0.3 -- which resolves the issues as it bundles the latest embedded Java driver which is in turn using the latest MongoDB embedded SDK ABI.